### ISSUE TITLE
Missing definition of $RABBIT_PORT

### ISSUE THREAD

**Issue by jenkin** [docker-taiga/back#1]
In config.py there is a `$RABBIT_PORT` not mentioned in start.sh or in docker-compose file. It should have the default value `5672`, otherwise an error can occur in taiga-back: `ValueError: invalid literal for int() with base 10: '$RABBIT_PORT'`.

**Comment by w1ck3dg0ph3r** [comment]
Thanks! Fixed in 3847368395cfca3575895679955d027ac8d20061.
