### ISSUE TITLE
Redis password is always 'password'

### ISSUE THREAD

**Issue by ichasco** [docker-taiga/back#10]
The redis password is always "password". Even though you set a different one in the environments.

Thanks

**Comment by w1ck3dg0ph3r** [comment]
Hi! Configs are generated using environment variables on the first run only. Changing env vars afterwards will have no effect, you'll have to modify configs yourself. Could that be the problem?

**Comment by ichasco** [comment]
Hi,

Yes, that was the problem. Thanks!
