### ISSUE TITLE
Restarting docker-compose wipes any changes made to config

### ISSUE THREAD

**Issue by zachiguess** [docker-taiga/back#7]
Whenever docker-compose gets restarted with changes made to the config (to put in SMTP parameters), it resets the config.py for taiga-back to scratch and locks it again like it does on the first-time setup. I am not taking it down and putting it up again, simply refreshing/restarting the containers themselves.

**Comment by w1ck3dg0ph3r** [comment]
Thanks! Reverted the responsible PR.

**Comment by zachiguess** [comment]
Hmm, it seems even after rebuilding my containers that I am still running into the same issue. Is there perhaps a step I am missing?

**Comment by w1ck3dg0ph3r** [comment]
Strange, can't reproduce this now. Some ideas:
- Did you remove old containers?
- Does image tags in `docker-compose.yml` match the ones on images you've built?
- Can you try pulling images from docker hub with `docker-compose pull`?

**Comment by zachiguess** [comment]
Ahh! It was not pulling the updated images. My brain is pretty fried because it took me a long time to realize the original problem wasn't a client-side error. Thanks again!
